services: 
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certs/:/etc/letsencrypt/:rw
    command: certonly -v --webroot --webroot-path /var/www/certbot -d always12.live
    