version: 1
disable_existing_loggers: False
formatters:
  default:
    # "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    # "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
filters:
  exclude_ffmpeg_log:
    (): utils.logging.FFmpegLogFilter  # Reference your custom filter class
  exclude_queue_list_endpoint:
    (): utils.logging.HealthCheckFilter  # Reference your custom filter class
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
    filters: [exclude_queue_list_endpoint]
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
  multipart.multipart:
    level: INFO
    handlers:
      - default
    propagate: no
root:
  level: DEBUG
  handlers:
    - default
  propagate: no
  filters: [exclude_ffmpeg_log, exclude_queue_list_endpoint]  # Apply the filter globally
# filters:
#   healthcheck_filter:
#     "()": utils.logging.HealthCheckFilter
# handlers:
#     console:
#         class: logging.StreamHandler
#         level: DEBUG
#         formatter: simple
#         filters:
#             - healthcheck_filter
#         stream: ext://sys.stdout