# For true migration between cluster creations, consider using:
# 1. Cloud-native storage (AWS EBS, GCE Persistent Disk, Azure Disk)
# 2. Distributed storage (Longhorn, OpenEBS, Rook/Ceph)
# 3. External database service (AWS RDS, Google Cloud SQL, etc.)

# Current setup uses hostPath which is node-specific and won't migrate between clusters
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: motherstream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv-staging
  namespace: motherstream
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/motherstream/Desktop/motherstream/staging/postgres-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv-staging
  namespace: motherstream
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/motherstream/Desktop/motherstream/staging/pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: motherstream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-initdb-pvc
  namespace: motherstream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-initdb-pv-staging
  namespace: motherstream
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/motherstream/Desktop/motherstream/staging/postgres-initdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stream-recordings-pv-staging
  namespace: motherstream
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/motherstream/Desktop/motherstream/staging/stream-recordings
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stream-recordings-pvc
  namespace: motherstream
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oryx-data-pv-staging
  namespace: motherstream
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/motherstream/Desktop/motherstream/staging/oryx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oryx-data-pvc
  namespace: motherstream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certs-pv-staging
  namespace: motherstream
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/motherstream/Desktop/motherstream/staging/certs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-pvc
  namespace: motherstream
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard 