apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: motherstream

resources:
  - ../../base
  - secrets.yaml
  - persistent-volumes.yaml

patchesStrategicMerge:
  - resource-patches.yaml
  - ingress-patch.yaml

namePrefix: prod-

images:
  - name: 192.168.49.1:5000/motherstream
    newTag: v1.0.0
  - name: 192.168.49.1:5000/frontend
    newTag: v1.0.0
  - name: nginx-rtmp
    newTag: v1.0.0

replicas:
  - name: postgres
    count: 1
  - name: motherstream
    count: 2
  - name: frontend
    count: 2
  - name: nginx-rtmp
    count: 1
  - name: oryx
    count: 1
  - name: jaeger
    count: 1

commonLabels:
  environment: production
  
configMapGenerator:
  - name: production-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
      - HEALTH_CHECK_INTERVAL=30s