apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmaps/motherstream-cm.yaml
  - configmaps/nginx-cm.yaml
  - deploys/jaeger.yaml
  - deploys/nginx-rtmp.yaml
  - deploys/oryx.yaml
  - deploys/motherstream.yaml
  - deploys/frontend.yaml
  - network/rtmp-ingress.yaml
  

commonLabels:
  project: motherstream
  
images:
  - name: 192.168.49.1:5000/motherstream
    newTag: latest
  - name: 192.168.49.1:5000/frontend
    newTag: latest
  - name: nginx-rtmp
    newTag: latest 